---
title: "Build-a-Dashboard Workshop (with Quarto, R and/or Python)*"
format: html
---

You already analyze and summarize your data in computational notebooks with R and/or Python. What’s next? You can share your insights or allow others to make their own conclusions in eye-catching dashboards and straight-forward to author, design, and deploy Quarto Dashboards, regardless of the language of your data processing, visualization, analysis, etc. With Quarto Dashboards, you can create elegant and production-ready dashboards using a variety of components, including static graphics (ggplot2, Matplotlib, Seaborn, etc.), interactive widgets (Plotly, Leaflet, Jupyter Widgets, htmlwidgets, etc.), tabular data, value boxes, text annotations, and more. Additionally, with intelligent resizing of components, your Quarto Dashboards look great on devices of all sizes. And importantly, you can author Quarto Dashboards without leaving the comfort of your “home” – in plain text markdown with any text editor (VS Code, RStudio, Neovim, etc.) or any notebook editor (JupyterLab, etc.).

This workshop will walk you through building an increasingly complex dashboard using various layout options and deploy them as static web pages (with no special server required) as well as with a Shiny Server on the backend for enhanced interactivity.

This course is for you if you:

* do data analysis in computational notebooks
* share your results with your audience in static or interactive dashboards
* want to improve the design, user interface, and experience of your dashboards

## Course Links
* [Website](https://posit-conf-2024.github.io/quarto-dashboards/)
* [GitHub](https://github.com/posit-conf-2024/quarto-dashboards)
* Example Olympic Dashboard
  + [GitHub](https://github.com/posit-conf-2024/olympicdash)
  + [R Version](https://mine.quarto.pub/olympic-games-r/)
  + [Python Version](https://mine.quarto.pub/olympic-games-py)
* [Quarto Guide](https://quarto.org/docs/guide/)

## Notes
* css for bootswatch: [https://github.com/thomaspark/bootswatch/tree/v5/dist](https://github.com/thomaspark/bootswatch/tree/v5/dist)
* Parameterized Quarto Reports Improve Understanding of Soil Health - posit::conf(2023): [https://www.youtube.com/watch?v=lbE5uOqfT70](https://www.youtube.com/watch?v=lbE5uOqfT70)