---
title: "DevOps for Data Scientists"
format: html
---

In this course we will learn the key principles of DevOps and problems which it intends to solve for data scientists. We will discuss how DevOps practices such as CI/CD enhance collaboration, automation, and reproducibility. We will learn common workflows for environment management, package management, containerization, monitoring & logging, and version control. Participants will get hands-on experience with a variety of tools including Docker, Github Actions, and APIs. Posit Pro Products will also be used by participants to quickly create and deploy R or python code using DevOps pipelines.

Please note that this course is not prescriptive around DevOps tools which are constantly growing and changing. Given that, the exact tools that will be used in this course (e.g. Jenkins, Azure Devops, etc) are subject to change.

This course is for you if you:

* Want to learn the main principles and tools of DevOps
* Are a data scientist who wants to put their R/Python code into production or work more closely with DevOps teams
* Want to get hands-on experience using docker, CI/CD tools, and other DevOps workflows.

## Course Links
* [GitHub](https://github.com/posit-conf-2024/dev-ops)
* [Exercises](https://rpubs.com/kbodwin/devops-mirror-ex)
* [Slides](https://kelly-bodwin.quarto.pub/slides-for-devops-workshop/)