---
title: "Introduction to Shiny for R"
format: html
---

Shiny is an R package that makes it easy to build interactive web apps straight from R. This workshop will start at the beginning: designing and creating user interfaces, learning and mastering the reactive model that connects your R code to the interface, and deploying apps publicly and privately. We will wrap up with some intermediate-level tools: debugging and modularizing your apps and implementing dynamic user interfaces. In the end, you’ll be a confident Shiny user, able to design interactive apps to achieve your purpose and produce a polished and professional implementation.

This workshop is for you if you:

-   are comfortable with the basics of R, such as writing functions, indexing vectors and lists, debugging simple errors, and working with data structures like data frames,
-   are interested in creating interactive web applications, and
-   have no or minimal experience with Shiny for R. If you have a bit of experience, you’ll see things in a new way. If you don’t, we’ll get you started on the right footing.

## Course Links

-   [GitHub](https://posit-conf-2024.github.io/shiny-r-intro/)

## Notes

-   Joe Cheng \| The Past and Future of Shiny \| RStudio (2022): <https://www.youtube.com/watch?v=HpqLXB_TnpI>
