---
title: "Introduction to tidymodels*"
format: html
---

This workshop will teach you core tidymodels packages and their uses: data splitting/resampling with rsample, model fitting with parsnip, measuring model performance with yardstick, and basic pre-processing with recipes. Time permitting, you’ll be introduced to model optimization using the tune package. You’ll learn tidymodels syntax as well as the process of predictive modeling for tabular data.

This workshop is for you if you:

-   are comfortable using tidyverse packages to read data into R, transform and reshape data, and make a variety of graphs, and
-   have had some exposure to basic statistical concepts such as linear models, residuals, etc.

Intermediate or expert familiarity with modeling or machine learning is not required. Interested students who have intermediate or expert familiarity with modeling or machine learning may be interested in the Advanced tidymodels workshop.

## Course Links

-   [GitHub](https://github.com/posit-conf-2024/tidymodels-intro)

## Notes

-   Tidy modeling with R Book: <https://www.tmwr.org/>
