---
title: "Making Tables with gt and Great Tables*"
format: html
---

The gt package for R and the Great Tables package for Python both deal with an important element of written communication: tables. We don’t believe tables have to be drab or dull. Rather, we think that tables have the power to inspire and to excite!

In this workshop, you’ll learn about how to make tables that can accurately convey information yet look aesthetically pleasing. We will handle the first stumbling block: what do we even call the different parts of a table? After getting the table terminology down we’ll learn how to effectively assemble the table components and create powerful displays of information. We will start simply and progressively, working toward more complex table designs. Since there are two packages (one in R, one in Python) we will take a blended approach and learn about table generation in bilingual fashion.

We’ll cover the following:

* Create table components and put them together (e.g., header, footer, stub, etc.)
* Format cell values (numeric/scientific, date/datetime, etc.)
* Rearranging columns and handling column value alignments
* Styling the table, either through data values or on a more granular level
* Adding icons, plots, images, and incorporating your own HTML
more!

This course is for you if you:

* have some basic working knowledge of either R or Python (separate sets of materials will be available for both R and Python),
* have data you often need to present as data summaries
* would like to level-up your ability to generate tables for publication

## Course Links
* [GitHub](https://github.com/posit-conf-2024/tables)
* [Slides](https://github.com/posit-conf-2024/tables/blob/main/slides/tables_workshop_slides.pdf)