---
title: "R in Production"
format: html
---

What it means to put R in production varies tremendously from organisation to organisation. However, I believe that there are common principles that you can learn to improve your code, regardless of the precise details of what production means for your organisation.

This workshop is organised around three big differences between running a local script on your computer and putting your code into production:

* Not just once: production code isn’t a one-off script; it runs repeatedly, and needs to run reliably even as the environment around it (e.g. R package versions and input data) changes. How can you ensure that code continues to run reliably months and years after you wrote it, and when there’s a problem it clearly reports on it.
* Not just your computer: production code doesn’t run on your computer. It typically runs on some other server where you can’t interactively experiment. This poses particular challenges for authentication and debugging.
* Not just you: the responsibility for production code is typically shared across a team. How can you ensure that you’re all working together as effectively as possible, sharing code and best practices, and continuing to get better at your job over time.

This course is for you if you:

* Get frustrated debugging R code that’s running on another computer.
* Struggle keep your code running reliably as packages and data change over time.
* Want to generally improve the quality of your production code.

## Course Links
* [GitHub](https://github.com/posit-conf-2024/r-in-production)